export const LINKEDIN_URL = 'https://www.linkedin.com/company/toona-studio/'
export const INSTAGRAM_URL = 'https://www.instagram.com/toona.studio/'
export const DISCORD_URL = 'https://discord.gg/pbHNpDTCXz'
export const WEBSITE_URL = 'https://christoona.com/'
export const DRIBBBLE_URL = 'https://dribbble.com/christoona'
